use sakila;
-- 1. List the number of films per category.
select count(f.film_id) as number_of_films, c.name as category
from category c
JOIN film_category f
on  c.category_id = f.category_id
group by c.name
order by number_of_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT 
    s.store_id,
    c.city AS city_name,
    co.country AS country_name
FROM store s
JOIN address a
    ON s.address_id = a.address_id
JOIN city c
    ON a.city_id = c.city_id
JOIN country co
    ON c.country_id = co.country_id
ORDER BY s.store_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) total_revenue
FROM store s 
JOIN staff st
on s.store_id = st.store_id
JOIN payment p 
on p.staff_id = st.staff_id
group by s.store_id
order by total_revenue DESC;

-- 4. Determine the average running time of films for each category.
SELECT round(avg(f.length), 2) as average_running_time, c.name as category_name
FROM film f 
JOIN film_category fc
on f.film_id = fc.film_id
JOIN category c
on fc.category_id = c.category_id
GROUP BY category_name
ORDER BY category_name; 

-- 5. Identify the film categories with the longest average running time. (Did top 5)
SELECT round(avg(f.length), 2) as average_running_time, c.name as category_name
FROM film f 
JOIN film_category fc
on f.film_id = fc.film_id
JOIN category c
on fc.category_id = c.category_id
GROUP BY category_name
ORDER BY average_running_time DESC
LIMIT 5; 

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT f.title as movie_title, COUNT(r.rental_id) as rental_count
FROM film f 
JOIN inventory i 
on i.film_id = f.film_id
JOIN rental r 
on r.inventory_id = i.inventory_id
GROUP BY f.film_id, f.title
order by rental_count DESC
limit 10; 

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT f.title, i.store_id, count(i.inventory_id) AS total_copies, SUM(CASE
		WHEN r.rental_id IS NULL THEN 1
        ELSE 0
        END) AS available_copies
FROM film f 
JOIN inventory i 
on f.film_id = i.film_id
LEFT JOIN rental r 
on i.inventory_id = r.inventory_id
and r.return_date IS NULL
WHERE f.title = "ACADEMY DINOSAUR" 
and i.store_id = 1
GROUP BY f.title, i.store_id;
/*
-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
	Include a column indicating whether each title is 'Available' or 'NOT available.' 
	Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL */
SELECT 
    f.title,
    CASE 
        WHEN IFNULL(MAX(i.inventory_id), 0) = 0 THEN 'Not available'
        ELSE 'Available'
    END AS availability
FROM film f
LEFT JOIN inventory i
    ON f.film_id = i.film_id
GROUP BY f.film_id, f.title
ORDER BY f.title;